### PR TITLE
UI changes, small improvements

### PR DESCRIPTION
**Pull request by MaximeHerpin**
Object and material selector, break chance, fixed obstacle avoidance

### CODE REVIEW

**Comment by ekaj2** [comment]
You deleted the update operator?

**Comment by MaximeHerpin** [comment]
Yes, there was a duplicate.

**Comment by ekaj2** [comment]
Is it ok to merge the preset removal pull request BEFORE fixing this conflict?

**Comment by ekaj2** [comment]
Want me to fix the conflict?

**Comment by MaximeHerpin** [comment]
Yes, I must say I'm a bit lost.

**Comment by ekaj2** [comment]
Alright, don't worry about it for now...I will get to it soon.

**Comment by MaximeHerpin** [comment]
Thank's

**Comment by ekaj2** [comment]
There you go...please look it over and merge it if it looks right to you :)

**Comment by ekaj2** [comment]
We really need to move to this plan so the merge conflicts are fewer and farther between:

http://nvie.com/posts/a-successful-git-branching-model/

Please let me know if you are fine with me trying to set that up on the master repo. Also, let me know of course if you have any questions about the article.

**Comment by MaximeHerpin** [comment]
The branching model seems great, I'm totally fine with you setting it up !

**Comment by ekaj2** [comment]
I just saw the network tab:

https://github.com/MaximeHerpin/Blender-Modular-tree-addon/network

You can see pretty easily why there are so many conflicts :)

**Pull request merged**
